//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUnitTestProjectSplitter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUnitTestProjectSplitter.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;DifferentCategoryProject.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedDifferentCategoryProject_AssemblyCategory {
            get {
                return ResourceManager.GetString("ExpectedDifferentCategoryProject_AssemblyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;DifferentCategoryProject.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedDifferentCategoryProject_MultipleCategory {
            get {
                return ResourceManager.GetString("ExpectedDifferentCategoryProject_MultipleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;DifferentCategoryProject.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedDifferentCategoryProject_TestCategory {
            get {
                return ResourceManager.GetString("ExpectedDifferentCategoryProject_TestCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;DifferentCategoryProject.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedDifferentCategoryProject_TestClassCategory {
            get {
                return ResourceManager.GetString("ExpectedDifferentCategoryProject_TestClassCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;DifferentCategoryProject.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedDifferentCategoryProject_TestFixtureCategory {
            get {
                return ResourceManager.GetString("ExpectedDifferentCategoryProject_TestFixtureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;Project1.IsolatedTests.dll&quot; /&gt;
        ///    &lt;assembly path=&quot;Project1.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedIsolatedTestProject {
            get {
                return ResourceManager.GetString("ExpectedIsolatedTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;Project1.ParallelTests.dll&quot; /&gt;
        ///    &lt;assembly path=&quot;Project1.Tests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedParallelTestProject {
            get {
                return ResourceManager.GetString("ExpectedParallelTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;NUnitProject&gt;
        ///  &lt;Settings activeconfig=&quot;D2L&quot; /&gt;
        ///  &lt;Config name=&quot;CustomConfig&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;Project1.UnitTests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///  &lt;Config name=&quot;D2L&quot; binpathtype=&quot;Auto&quot;&gt;
        ///    &lt;assembly path=&quot;Project1.Tests.dll&quot; /&gt;
        ///    &lt;assembly path=&quot;Project1.UnitTests.dll&quot; /&gt;
        ///  &lt;/Config&gt;
        ///&lt;/NUnitProject&gt;.
        /// </summary>
        internal static string ExpectedUnitTestProjects {
            get {
                return ResourceManager.GetString("ExpectedUnitTestProjects", resourceCulture);
            }
        }
    }
}
